os: linux
dist: focal
language: generic

env:
  jobs:
    - LISP=sbcl
    - LISP=ccl
    - LISP=ecl
    - LISP=abcl
    - LISP=clisp
    # - LISP=allegro
    # - LISP=ccl32
    # - LISP=sbcl32
    # - LISP=cmucl

matrix:
  fast_finish: true
  allow_failures:
    - env: LISP=ccl32
    - env: LISP=sbcl32
    # - env: LISP=cmucl

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#iolib"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true

install:
  - curl -L https://raw.githubusercontent.com/lispci/cl-travis/master/install.sh | sh
  - cl -e "(cl:in-package :cl-user)
           (dolist (p '(:trivial-features :fiveam))
             (ql:quickload p :verbose t))"

script:
  - cl -e "(cl:in-package :cl-user)
           (print (lisp-implementation-version))(terpri)
           (ql:quickload :swap-bytes/test :verbose t)
           (uiop:quit (if (5am:run! :bordeaux-threads-2) 0 -1))"
