@node Overview
@chapter Overview

Describe this library here.

@node IO Streams
@chapter IO Streams

@section Stream Classes

@include include/class-io.streams-dual-channel-gray-stream.texinfo
@include include/class-io.streams-dual-channel-single-fd-gray-stream.texinfo
@include include/class-io.streams-dual-channel-fd-mixin.texinfo
@include include/class-io.streams-dual-channel-single-fd-mixin.texinfo

@section Stream Accessors

@include include/fun-io.streams-fd-non-blocking.texinfo
@include include/fun-io.streams-input-fd-non-blocking.texinfo
@include include/fun-io.streams-output-fd-non-blocking.texinfo
