on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, windows ]
  pull_request:
    branches: [ main, windows ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SBCL
        run: |
          curl -L -O "https://downloads.sourceforge.net/project/sbcl/sbcl/2.3.4/sbcl-2.3.4-x86-64-linux-binary.tar.bz2"
          tar -xf sbcl-2.3.4-x86-64-linux-binary.tar.bz2
          cd sbcl-2.3.4-x86-64-linux
          ./install.sh --prefix=$HOME/.local
          cd ..
          rm -rf sbcl-2.3.4-x86-64-linux-binary.tar.bz2 sbcl-2.3.4-x86-64-linux
        shell: bash
      - name: Build and Install
        run: |
          sbcl --load setup.lisp
          ocicl setup > ~/.sbclrc
          echo "(setf ocicl-runtime:*verbose* t)" >> ~/.sblrc
        shell: bash
      - name: Test
        run: |
          rm -rf systems systems.csv
          mkdir test
          cd test
          touch systems.ocicl
          ocicl install sento
          ls -l systems
          ls -l systems.ocicl
          cat systems.ocicl
          sbcl --non-interactive --eval "(asdf:load-system :sento)" --eval "(quit)"
          sbcl --non-interactive --eval "(asdf:load-system :cl-etcd)" --eval "(quit)"
          rm -rf systems
          ocicl install
          ocicl latest
        shell: bash
