on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: '*'
  pull_request:
    branches: [ main, windows ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SBCL
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install sbcl

      - uses: actions/cache@v4
        with:
          path: |
            systems
            ~/.cache/common-lisp
          key: ${{ runner.os }}-ocicl-${{ hashFiles('systems.csv') }}
          restore-keys: |
            ${{ runner.os }}-ocicl-

      - name: Build and Install
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sbcl --load setup.lisp
          ocicl version
          ocicl setup > ~/.sbclrc
          echo "(setf ocicl-runtime:*verbose* nil)" >> ~/.sblrc
        shell: bash

      - name: Test
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          rm -rf systems systems.csv ocicl
          mkdir test
          cd test
          ocicl new cli-test cli
          cd cli-test
          make
          ./cli-test --help
        shell: bash
