on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: '*'
  pull_request:
    branches: [ main, windows ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SBCL
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install sbcl

      - uses: actions/cache@v4
        with:
          path: |
            systems
            ~/.cache/common-lisp
          key: ${{ runner.os }}-ocicl-${{ hashFiles('systems.csv') }}
          restore-keys: |
            ${{ runner.os }}-ocicl-

      - name: Build and Install
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sbcl --load setup.lisp
          ocicl version
          ocicl setup > ~/.sbclrc
          echo "(setf ocicl-runtime:*verbose* nil)" >> ~/.sblrc
        shell: bash

      - name: Prepare test environment
        run: rm -rf systems systems.csv

      - name: Test cli Template
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          rm -rf testdir && mkdir testdir && cd testdir
          ocicl new cli-test cli
          cd cli-test
          make
          ./cli-test --help
        shell: bash

      - name: Test web1 Template
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          rm -rf testdir && mkdir testdir && cd testdir
          ocicl new web1-test web1
          cd web1-test
          make
          ./web1-test --help
          ./web1-test -p 8765 &
          APP_PID=$!
          for i in {1..30}; do
            curl --silent --fail http://localhost:8765/ && break
            echo "Waiting for web1.." && sleep 1
          done
          curl -v http://localhost:8765/ | grep "Welcome"
          kill $APP_PID
        shell: bash

      - name: Test basic Template
        run: |
          set -x
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          rm -rf testdir && mkdir testdir && cd testdir
          ocicl new basic-test cli
          cd basic-test
          sbcl --eval "(asdf:load-system :basic-test)" --eval "(basic-test:main)" --eval "(uiop:quit 0)" | grep -v "Hello, world"
        shell: bash
