on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ windows ]
  pull_request:
    branches: [ windows ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
       include:
         - SBCL_VERSION: 2.4.9
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          install: make unzip
      - name: download SBCL
        run: wget https://downloads.sourceforge.net/project/sbcl/sbcl/${{ matrix.SBCL_VERSION }}/sbcl-${{ matrix.SBCL_VERSION }}-x86-64-windows-binary.msi
      - name: install SBCL
        # for unknown reason, msiexec pops up a window under msys2, so use cmd instead
        shell: cmd
        run: msiexec /a sbcl-${{ matrix.SBCL_VERSION }}-x86-64-windows-binary.msi TARGETDIR=C:\sbcl /qn
      - name: Set git to use LF
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - name: Build and Install (bash)
        shell: bash
        run: |
          SBCL=/c/sbcl/Pfiles/"Steel Bank Common Lisp"/sbcl.exe /c/sbcl/Pfiles/"Steel Bank Common Lisp"/sbcl.exe --load setup.lisp
          echo "================================================================================"
          /c/sbcl/Pfiles/"Steel Bank Common Lisp"/sbcl.exe --dynamic-space-size 3072 --no-userinit --eval "(load \"runtime/asdf.lisp\")" --eval "(progn (asdf:initialize-source-registry (list :source-registry :inherit-configuration (list :tree (uiop:getcwd)))) (asdf:make :ocicl) (sb-ext:quit))"
      - name: Test
        run: |
          rm -rf systems systems.csv
          mkdir test
          cd test
          ../ocicl.exe install sento
          cat systems.csv
          ls -l systems
          /c/sbcl/Pfiles/"Steel Bank Common Lisp"/sbcl.exe --non-interactive --eval "(asdf:load-system :sento)" --eval "(quit)"
          /c/sbcl/Pfiles/"Steel Bank Common Lisp"/sbcl.exe --non-interactive --eval "(asdf:load-system :cl-etcd)" --eval "(quit)"
          rm -rf systems
          ../ocicl.exe install
          ../ocicl.exe latest
        shell: bash
